language: go
go: 1.8.3
install: make setup
script: make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - git diff
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
notifications:
  email: false
